In [ ]:
import re

text1='your mail is abcA@gmail.com'
text2='another mail is aaccALS82@gmail.com'
text3='mobile number is:(949)-270-2871, mail is abun@gmail.com'
pattern='[a-zA-Z0-9]*@[a-z]*\.com'
pattern2='\(\d{3}\)-\d{3}-\d{4}|[a-zA-Z0-9]*@[a-z]*\.[a-z]*'
#date=re.findall(pattern,text2)
num=re.findall(pattern2,text3)
#date[0]
num

['(949)-270-2871', 'abun@gmail.com']

In [ ]:
text='june 28 1971 (age 50)'
pattern1='age (\d+)'
age=re.findall(pattern1,text)
age

['50']

SPACY

In [ ]:
!pip install spacy

In [ ]:
import spacy
nlp=spacy.blank('en')
txt=nlp('Everyone has to learn NLP properly with detailed text encoding concepts')
for i in txt:
  print(i)


Everyone
has
to
learn
NLP
properly
with
detailed
text
encoding
concepts


In [ ]:
nlp=spacy.blank('de')
text=nlp('Everyone has to learn NLP properly with detailed text encoding concepts')
for i in text:
  print(i,'-->','is_alpha:', i.is_alpha,
        'like_num:',i.like_num,
        'is_currency:',i.is_currency,
        'like_email:',i.like_email)
text[0]

Everyone --> is_alpha: True like_num: False is_currency: False like_email: False
has --> is_alpha: True like_num: False is_currency: False like_email: False
to --> is_alpha: True like_num: False is_currency: False like_email: False
learn --> is_alpha: True like_num: False is_currency: False like_email: False
NLP --> is_alpha: True like_num: False is_currency: False like_email: False
properly --> is_alpha: True like_num: False is_currency: False like_email: False
with --> is_alpha: True like_num: False is_currency: False like_email: False
detailed --> is_alpha: True like_num: False is_currency: False like_email: False
text --> is_alpha: True like_num: False is_currency: False like_email: False
encoding --> is_alpha: True like_num: False is_currency: False like_email: False
concepts --> is_alpha: True like_num: False is_currency: False like_email: False


Everyone

In [ ]:
doc=nlp('tony gave two dollar to peter')
doc

tony gave two dollar to peter

In [ ]:
token=doc[0]
token

tony

In [ ]:
type(token)

spacy.tokens.token.Token

In [ ]:
dir(token)

['_',
 '__bytes__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 'ancestors',
 'check_flag',
 'children',
 'cluster',
 'conjuncts',
 'dep',
 'dep_',
 'doc',
 'ent_id',
 'ent_id_',
 'ent_iob',
 'ent_iob_',
 'ent_kb_id',
 'ent_kb_id_',
 'ent_type',
 'ent_type_',
 'get_extension',
 'has_dep',
 'has_extension',
 'has_head',
 'has_morph',
 'has_vector',
 'head',
 'i',
 'idx',
 'iob_strings',
 'is_alpha',
 'is_ancestor',
 'is_ascii',
 'is_bracket',
 'is_currency',
 'is_digit',
 'is_left_punct',
 'is_lower',
 'is_oov',
 'is_punct',
 'is_quote',
 'is_right_punct',
 'is_sent_end',
 'is_sent_start',
 'is_space',
 'is_stop',
 'is_title',
 'is_upper',
 'lang',
 'lang_',
 'le

In [ ]:
token2=doc[2]
token2

two

In [ ]:
token2.like_num

True

In [ ]:
doc1=nlp('$')
token3=doc1[0]
token3.is_currency


True

In [ ]:
for token in doc:
  print(token,'==>','index:', token.i,
        'is_alpha:',token.is_alpha,
        'is_punct:', token.is_punct,
        'like_num:',token.like_num,
        'is_currency',token.is_currency)

tony ==> index: 0 is_alpha: True is_punct: False like_num: False is_currency False
gave ==> index: 1 is_alpha: True is_punct: False like_num: False is_currency False
two ==> index: 2 is_alpha: True is_punct: False like_num: True is_currency False
dollar ==> index: 3 is_alpha: True is_punct: False like_num: False is_currency False
to ==> index: 4 is_alpha: True is_punct: False like_num: False is_currency False
peter ==> index: 5 is_alpha: True is_punct: False like_num: False is_currency False


EXTRACTING FROM TEXT FILE


In [ ]:
with open('details.txt','r') as f:
  text=f.readlines()

In [ ]:
text

['details:\n',
 'mail of student: abc@gmail.com\n',
 'num: 7237472474\n',
 '\n',
 'mail of student2: priya@gmail.com\n',
 'num: 57487555465\n',
 '\n',
 'mail of student3: revi@gmail.com\n',
 'num: 45145487416']

In [ ]:
text=' '.join(text)
text

'details:\n mail of student: abc@gmail.com\n num: 7237472474\n \n mail of student2: priya@gmail.com\n num: 57487555465\n \n mail of student3: revi@gmail.com\n num: 45145487416'

In [ ]:
emails=[]
doc=nlp(text)
for i in doc:
  if i.like_email:
    emails.append(i)
emails

[abc@gmail.com, priya@gmail.com, revi@gmail.com]

In [ ]:
num=[]
for i in doc:
  if i.like_num:
    num.append(i)
num

[7237472474, 57487555465, 45145487416]

In [ ]:
doc1=nlp('gimme double cheese extra large bruger and perfectly roasted sandwich')
text1=[i.text for i in doc1]
text1

['gimme',
 'double',
 'cheese',
 'extra',
 'large',
 'bruger',
 'and',
 'perfectly',
 'roasted',
 'sandwich']

In [ ]:
#now let's apply tokenizer. The tokenizet used to modify the word wither by splitting or converting text into another form.
from spacy.symbols import ORTH
nlp.tokenizer.add_special_case('gimme',[
                               {ORTH:'gim'},
                               {ORTH:'me'}])
doc1=nlp('gimme double cheese extra large bruger and perfectly roasted sandwich')
token1=[i.text for i in doc1]
token1

['gim',
 'me',
 'double',
 'cheese',
 'extra',
 'large',
 'bruger',
 'and',
 'perfectly',
 'roasted',
 'sandwich']

In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:

nlp=spacy.load('en_core_web_sm')

In [ ]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7aebf7e6e200>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7aebf7e6cbe0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7aebf7a75850>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7aebf6ed7e80>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7aebf7030ec0>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7aebf7a757e0>)]

In [ ]:
#spacy.blank('en)
#spacy.blank('de')
#spacy.load('en_core_web_sm)
#spacy.load(en_core_web_sm)

POS-parts of speech

In [ ]:
nlp1=spacy.load('en_core_web_sm')

In [ ]:
nlp1.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
nlp1.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7aebf92eb820>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7aebf92eb040>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7aebf8e25a10>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7aebf8f8c140>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7aebf7e33380>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7aebf8e255b0>)]

In [ ]:
doc=nlp('captian america ate 10$ samosa, he said i can do that whole day!')
for i in doc:
  print(i, '|', i.pos_,'|',i.lemma_)



captian | PROPN | captian
america | PROPN | america
ate | VERB | eat
10 | NUM | 10
$ | SYM | $
samosa | NOUN | samosa
, | PUNCT | ,
he | PRON | he
said | VERB | say
i | PRON | I
can | AUX | can
do | VERB | do
that | DET | that
whole | ADJ | whole
day | NOUN | day
! | PUNCT | !


In [ ]:
nlp2=spacy.load('en_core_web_sm')
doc1=nlp2('Today atmosphere is not good, actually i planned to go dellas for an important business meeting.')
for token in doc1:
  print(token, '|', token.pos_,'|', token.lemma_)


Today | NOUN | today
atmosphere | NOUN | atmosphere
is | AUX | be
not | PART | not
good | ADJ | good
, | PUNCT | ,
actually | ADV | actually
i | PRON | I
planned | VERB | plan
to | PART | to
go | VERB | go
dellas | NOUN | della
for | ADP | for
an | DET | an
important | ADJ | important
business | NOUN | business
meeting | NOUN | meeting
. | PUNCT | .


In [ ]:
for i in doc1.ents:
  print(i.text, '|', i.label_,'|',spacy.explain(i.label_))

Today | DATE | Absolute or relative dates or periods


In [ ]:
doc3=nlp('Tesla Inc is going to acquire twitter for $45 billion')
for ent in doc3.ents:
  print(ent.text,'|',ent.label_,'|',spacy.explain(ent.label_))

Tesla Inc | ORG | Companies, agencies, institutions, etc.
$45 billion | MONEY | Monetary values, including unit


In [ ]:
from spacy import displacy
displacy.render(doc3,style='ent')

'<div class="entities" style="line-height: 2.5; direction: ltr">\n<mark class="entity" style="background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    Tesla Inc\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">ORG</span>\n</mark>\n is gpoing to acquire twitter for \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    $45 billion\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">MONEY</span>\n</mark>\n</div>'

In [ ]:
with open('details.txt','r') as f:
  text=f.readlines()
text

['details:\n',
 'mail of student: abc@gmail.com\n',
 'num: 7237472474\n',
 '\n',
 'mail of student2: priya@gmail.com\n',
 'num: 57487555465\n',
 '\n',
 'mail of student3: revi@gmail.com\n',
 'num: 45145487416']

In [ ]:
text=' '.join(text)
text

'details:\n mail of student: abc@gmail.com\n num: 7237472474\n \n mail of student2: priya@gmail.com\n num: 57487555465\n \n mail of student3: revi@gmail.com\n num: 45145487416'

In [ ]:
doc=nlp(text)
for ent in doc.ents:
  print(ent.text,'|',ent.label_,'|',spacy.explain(ent.label_))


7237472474 | CARDINAL | Numerals that do not fall under another type
57487555465 | CARDINAL | Numerals that do not fall under another type
45145487416 | CARDINAL | Numerals that do not fall under another type


In [ ]:
from spacy import displacy
displacy.render(doc,style='ent')

'<div class="entities" style="line-height: 2.5; direction: ltr">details:<br> mail of student: abc@gmail.com<br> num: \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    7237472474\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">CARDINAL</span>\n</mark>\n<br> <br> mail of student2: priya@gmail.com<br> num: \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    57487555465\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">CARDINAL</span>\n</mark>\n<br> <br> mail of student3: revi@gmail.com<br> num: \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    45145487416

In [ ]:
nlp=spacy.load('en_core_web_sm')
doc2=nlp('eating eats eat ate adjustable rafting ability meeting')
for i in doc2:
  print(i,'|',i.pos_,'|',i.lemma_)



eating | VERB | eat
eats | NOUN | eat
eat | VERB | eat
ate | VERB | eat
adjustable | ADJ | adjustable
rafting | VERB | raft
ability | NOUN | ability
meeting | NOUN | meeting


In [ ]:
doc4=nlp('mando talked for 3 hours although rafting is not his thing he became talkative')
for ent in doc4.ents:
  print(ent,'|',ent.label_,'|',spacy.explain(ent.label_))

3 hours | TIME | Times smaller than a day


In [ ]:
from spacy import displacy
displacy.render(doc4,style='ent')

'<div class="entities" style="line-height: 2.5; direction: ltr">mando talked for \n<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    3 hours\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">TIME</span>\n</mark>\n although rafting is not his thing he became talkative</div>'

In [ ]:
for token in doc4:
  print(doc4.text,'|',token.lemma_,'|',token.lemma)

mando talked for 3 hours although rafting is not his thing he became talkative | mando | 10991835832878170099
mando talked for 3 hours although rafting is not his thing he became talkative | talk | 13939146775466599234
mando talked for 3 hours although rafting is not his thing he became talkative | for | 16037325823156266367
mando talked for 3 hours although rafting is not his thing he became talkative | 3 | 602994839685422785
mando talked for 3 hours although rafting is not his thing he became talkative | hour | 9748623380567160636
mando talked for 3 hours although rafting is not his thing he became talkative | although | 343236316598008647
mando talked for 3 hours although rafting is not his thing he became talkative | raft | 7154368781129989833
mando talked for 3 hours although rafting is not his thing he became talkative | be | 10382539506755952630
mando talked for 3 hours although rafting is not his thing he became talkative | not | 447765159362469301
mando talked for 3 hours alth

In [ ]:
nlp.pipe_names


['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7aebf73711e0>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7aebf73715a0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7aebf3de1770>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7aebf71dbec0>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7aebf7a4ee80>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7aebf3de2030>)]

In [ ]:
#pos-part of speech
nlp=spacy.load('en_core_web_sm')
for i in doc:
  print(i,'|',i.pos_,'|',spacy.explain(i.pos_),
        '|',i.tag_,'|',spacy.explain(i.tag_))


details | NOUN | noun | NNS | noun, plural
: | PUNCT | punctuation | : | punctuation mark, colon or ellipsis

  | SPACE | space | _SP | whitespace
mail | NOUN | noun | NN | noun, singular or mass
of | ADP | adposition | IN | conjunction, subordinating or preposition
student | NOUN | noun | NN | noun, singular or mass
: | PUNCT | punctuation | : | punctuation mark, colon or ellipsis
abc@gmail.com | X | other | ADD | email

  | SPACE | space | _SP | whitespace
num | PROPN | proper noun | NNP | noun, proper singular
: | PUNCT | punctuation | : | punctuation mark, colon or ellipsis
7237472474 | NUM | numeral | CD | cardinal number

 
  | SPACE | space | _SP | whitespace
mail | NOUN | noun | NN | noun, singular or mass
of | ADP | adposition | IN | conjunction, subordinating or preposition
student2 | PROPN | proper noun | NNP | noun, proper singular
: | PUNCT | punctuation | : | punctuation mark, colon or ellipsis
priya@gmail.com | X | other | ADD | email

  | SPACE | space | _SP | whitespac

In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7aebf91a3fa0>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7aebf91a2740>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7aebf4dd0200>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7aebf8049f80>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7aebf4e1f400>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7aebf4dd00b0>)]

In [ ]:
filtered_tokens=[]
for i in doc:
  if i.pos_ not in ['SPACE','X','PUNCT']:
    filtered_tokens.append(i)
filtered_tokens

[details,
 mail,
 of,
 student,
 num,
 7237472474,
 mail,
 of,
 student2,
 num,
 57487555465,
 mail,
 of,
 student3,
 num,
 45145487416]

In [ ]:
doc5=nlp('he will quit his job')
doc5[2]
print(doc5[2].text,'|',doc5[2].tag_,'|',spacy.explain(doc5[2].tag_))

quit | VB | verb, base form


SPAM MAIL CLASSIFICATION USING COUNT VECTORIZER

In [ ]:
import pandas as pd
d=pd.read_csv('/content/spam.csv', encoding_errors= 'replace')
df=pd.DataFrame(d)
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [ ]:
df.shape

(5572, 5)

In [ ]:
df['spam']=df['v1'].apply(lambda x:1 if x== 'spam' else 0)


In [ ]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  spam  
0           NaN        NaN     0  
1           NaN        NaN     0  
2           NaN        NaN     1  
3           NaN        NaN     0  
4           NaN        NaN     0  
...         ...        ...   ...  
5567        NaN        NaN     1  
5568        NaN        NaN     0  
5569        NaN        NaN     0  
5570        NaN        NaN     0  
5571        NaN        NaN     0  

[5572 rows x 6 columns]

In [ ]:
df.shape

(5572, 6)

In [ ]:
x=df.iloc[:,2:3]

In [ ]:
x.shape

(5572, 1)

In [ ]:
y=df.iloc[:,5:]

In [ ]:
y.shape

(5572, 1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.v2,df.spam,test_size=0.2)

In [ ]:
x_train.shape

(4457,)

In [ ]:
x_test.shape

(1115,)

In [ ]:
y_train.shape

(4457,)

In [ ]:
y_test.shape

(1115,)

In [ ]:
x_train[:4]

4526    Understand. his loss is my gain :) so do you w...
2252                 Den wat will e schedule b lk on sun?
665     En chikku nange bakra msg kalstiya..then had t...
1657    S:-)if we have one good partnership going we w...
Name: v2, dtype: object

In [ ]:
x_train.head()

4526    Understand. his loss is my gain :) so do you w...
2252                 Den wat will e schedule b lk on sun?
665     En chikku nange bakra msg kalstiya..then had t...
1657    S:-)if we have one good partnership going we w...
514     You are guaranteed the latest Nokia Phone, a 4...
Name: v2, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()

In [ ]:
x_train_cv=cv.fit_transform(x_train)

In [ ]:
x_train_cv

<4457x7675 sparse matrix of type '<class 'numpy.int64'>'
	with 59033 stored elements in Compressed Sparse Row format>

In [ ]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_train_cv.shape

(4457, 7675)

In [ ]:
x_train.head()

4979                               So what u doing today?
296     Unless it's a situation where YOU GO GURL woul...
3051    Please leave this topic..sorry for telling that..
3206            This phone has the weirdest auto correct.
2579       I dunno until when... Lets go learn pilates...
Name: v2, dtype: object

In [ ]:
x_train_np=x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
import numpy as np
np.where(x_train_np[0]!=0)

(array([2390, 6222, 6888, 7403]),)

In [ ]:
cv.get_feature_names_out()[6600]

'sunscreen'

In [ ]:
x_train[:4][3206]

'This phone has the weirdest auto correct.'

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [ ]:
x_test_cv=cv.transform(x_test)

In [ ]:
x_test_cv.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
x_test_cv.shape

(1115, 7675)

In [ ]:
cv.get_feature_names_out()[6800]

'thirunelvali'

In [ ]:
print(x_train_cv.shape)
x_test_cv.shape

(4457, 7675)


(1115, 7675)

In [ ]:
model.fit(x_train_cv,y_train)

MultinomialNB()

In [ ]:
y_pred=model.predict(x_test_cv)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       976
           1       0.92      0.95      0.93       139

    accuracy                           0.98      1115
   macro avg       0.95      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
x_train[:][1400]

'No, I decided that only people who care about stuff vote and caring about stuff is for losers'

In [ ]:
x_train[2252]

'Den wat will e schedule b lk on sun?'

In [ ]:
email=["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",'Den wat will e schedule b lk on sun?']
email_count=cv.transform(email)
model.predict(email_count)

array([1, 0])

In [ ]:
emails=['SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info','XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL','K tell me anything about you.']
email_counts=cv.transform(emails)
model.predict(email_counts)

array([1, 1, 0])

In [ ]:
emails=["Did you hear about the new \Divorce Barbie\"? It comes with all of Ken's stuff!",'Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed �1000 cash or �5000 prize!','HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX','Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed �1000 cash or �5000 prize!']
email_counts=cv.transform(emails)
model.predict(email_counts)

array([0, 1, 0, 1])

**STOP WORDS**

In [ ]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
#from spacy.lang.en.stop_words import STOP_WORDS
len(STOP_WORDS)

326

In [ ]:
nlp=spacy.load('en_core_web_sm')
doc=nlp('I just want to select a good movie, iam searching from 2 hours but still iam losing my interest to find good movie of recently released')
for i in doc:
  if i.is_stop:
    print(i)

I
just
to
a
from
but
still
my
to
of


In [ ]:
def preprocess(text):
  doc=nlp(text)
  no_stop_word=[]
  for token in doc:
    if not token.is_stop:
      no_stop_word.append(token.text)
  return " ".join(no_stop_word)
preprocess('No, I decided that only people who care about stuff vote and caring about stuff is for losers')



', decided people care stuff vote caring stuff losers'

In [ ]:
def preprocess(text):
  doc=nlp(text)
  no_stop_words=[i.text for i in doc if not i.is_stop]
  return " ".join(no_stop_words)
preprocess('Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?')

'nt planning buy later . check lido got 530 e afternoon . U finish work ?'

In [ ]:
df=pd.read_json('/content/combined.json',lines=True)

In [ ]:
df.head(5)

id                                              title  \
0     None       Convicted Bomb Plotter Sentenced to 30 Years   
1  12-919   $1 Million in Restitution Payments Announced t...   
2  11-1002  $1 Million Settlement Reached for Natural Reso...   
3   10-015  10 Las Vegas Men Indicted \r\nfor Falsifying V...   
4   18-898  $100 Million Settlement Will Speed Cleanup Wor...   

                                            contents  \
0  PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...   
1    WASHINGTON – North Carolina’s Waccamaw River...   
2        BOSTON– A $1-million settlement has been...   
3    WASHINGTON—A federal grand jury in Las Vegas...   
4  The U.S. Department of Justice, the U.S. Envir...   

                        date         topics  \
0  2014-10-01T00:00:00-04:00             []   
1  2012-07-25T00:00:00-04:00             []   
2  2011-08-03T00:00:00-04:00             []   
3  2010-01-08T00:00:00-05:00             []   
4  2018-07-09T00:00:00-04:00  [Environment]   

                                     components  
0            [National Security Division (NSD)]  
1  [Environment and Natural Resources Division]  
2  [Environment and Natural Resources Division]  
3  [Environment and Natural Resources Division]  
4  [Environment and Natural Resources Division]

In [ ]:
df=df[df['topics'].str.len()!=0]
df


id                                              title  \
4       18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7      14-1412  14 Indicted in Connection with New England Com...   
19     17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22     15-1562  21st Century Oncology to Pay $19.75 Million to...   
23     17-1404  21st Century Oncology to Pay $26 Million to Se...   
...        ...                                                ...   
13081  14-1377  Yuba City, California, Man Sentenced to 46 Mon...   
13082   16-735  Yuengling to Upgrade Environmental Measures to...   
13084   17-045  Zimmer Biomet Holdings Inc. Agrees to Pay $17....   
13085   17-252  ZTE Corporation Agrees to Plead Guilty and Pay...   
13086   17-304  ZTE Corporation Pleads Guilty for  Violating U...   

                                                contents  \
4      The U.S. Department of Justice, the U.S. Envir...   
7      A 131-count criminal indictment was unsealed t...   
19     The United States Attorney’s Office for the Mi...   
22     21st Century Oncology LLC, has agreed to pay $...   
23     21st Century Oncology Inc. and certain of its ...   
...                                                  ...   
13081  Anthony Merrell Tyler, 34, of Yuba City, Calif...   
13082  The Department of Justice and the U.S. Environ...   
13084  Subsidiary Agrees to Plead Guilty to Violating...   
13085  ZTE Corporation has agreed to enter a guilty p...   
13086  ZTE Corporation pleaded guilty today to conspi...   

                            date  \
4      2018-07-09T00:00:00-04:00   
7      2014-12-17T00:00:00-05:00   
19     2017-12-14T00:00:00-05:00   
22     2015-12-18T00:00:00-05:00   
23     2017-12-12T00:00:00-05:00   
...                          ...   
13081  2014-12-09T00:00:00-05:00   
13082  2016-06-23T00:00:00-04:00   
13084  2017-01-12T00:00:00-05:00   
13085  2017-03-07T00:00:00-05:00   
13086  2017-03-22T00:00:00-04:00   

                                                  topics  \
4                                          [Environment]   
7                                  [Consumer Protection]   
19                                         [Environment]   
22                 [False Claims Act, Health Care Fraud]   
23                 [Health Care Fraud, False Claims Act]   
...                                                  ...   
13081                                      [Hate Crimes]   
13082                                      [Environment]   
13084                               [Foreign Corruption]   
13085  [Asset Forfeiture, Counterintelligence and Exp...   
13086           [Counterintelligence and Export Control]   

                                              components  
4           [Environment and Natural Resources Division]  
7                                       [Civil Division]  
19     [Environment and Natural Resources Division, U...  
22                                      [Civil Division]  
23              [Civil Division, USAO - Florida, Middle]  
...                                                  ...  
13081  [Civil Rights Division, Civil Rights - Crimina...  
13082       [Environment and Natural Resources Division]  
13084  [Criminal Division, Criminal - Criminal Fraud ...  
13085  [National Security Division (NSD), USAO - Texa...  
13086  [National Security Division (NSD), USAO - Texa...  

[4688 rows x 6 columns]

In [ ]:
df['new_content']=df.contents.apply(preprocess)

In [ ]:
df['new_content']

4        U.S. Department Justice , U.S. Environmental P...
7        131 - count criminal indictment unsealed today...
19       United States Attorney Office Middle District ...
22       21st Century Oncology LLC , agreed pay $ 19.75...
23       21st Century Oncology Inc. certain subsidiarie...
                               ...                        
13081    Anthony Merrell Tyler , 34 , Yuba City , Calif...
13082    Department Justice U.S. Environmental Protecti...
13084    Subsidiary Agrees Plead Guilty Violating Forei...
13085    ZTE Corporation agreed enter guilty plea pay $...
13086    ZTE Corporation pleaded guilty today conspirin...
Name: new_content, Length: 4688, dtype: object

In [ ]:
df.head()

id                                              title  \
4    18-898  $100 Million Settlement Will Speed Cleanup Wor...   
7   14-1412  14 Indicted in Connection with New England Com...   
19  17-1419  2017 Southeast Regional Animal Cruelty Prosecu...   
22  15-1562  21st Century Oncology to Pay $19.75 Million to...   
23  17-1404  21st Century Oncology to Pay $26 Million to Se...   

                                             contents  \
4   The U.S. Department of Justice, the U.S. Envir...   
7   A 131-count criminal indictment was unsealed t...   
19  The United States Attorney’s Office for the Mi...   
22  21st Century Oncology LLC, has agreed to pay $...   
23  21st Century Oncology Inc. and certain of its ...   

                         date                                 topics  \
4   2018-07-09T00:00:00-04:00                          [Environment]   
7   2014-12-17T00:00:00-05:00                  [Consumer Protection]   
19  2017-12-14T00:00:00-05:00                          [Environment]   
22  2015-12-18T00:00:00-05:00  [False Claims Act, Health Care Fraud]   
23  2017-12-12T00:00:00-05:00  [Health Care Fraud, False Claims Act]   

                                           components  \
4        [Environment and Natural Resources Division]   
7                                    [Civil Division]   
19  [Environment and Natural Resources Division, U...   
22                                   [Civil Division]   
23           [Civil Division, USAO - Florida, Middle]   

                                          new_content  
4   U.S. Department Justice , U.S. Environmental P...  
7   131 - count criminal indictment unsealed today...  
19  United States Attorney Office Middle District ...  
22  21st Century Oncology LLC , agreed pay $ 19.75...  
23  21st Century Oncology Inc. certain subsidiarie...

In [ ]:
preprocess('this is not a good movie')

'good movie'

In [ ]:
preprocess('this is a good movie')

'good movie'

In [ ]:
preprocess('how are you mr.krishna hope your doing well, actually ia, writing this note to address about your curriculum about studies and academic activites as well! do participate on everything you like')

'mr.krishna hope , actually ia , writing note address curriculum studies academic activites ! participate like'

TF-IDF vectorisation

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

#TF-term frequency defines number of times the word appears in the document and it ranges between 0 and 1
#TF= number of times word appeard /total number of words in the document
#IDF-represents Inverse document frequency and denotes the log of ratio of total number of documents.
#log(total number of documents/number of documents that contains the word)


In [ ]:
v=TfidfVectorizer()

In [ ]:
transform_ouput=v.fit_transform(corpus)

In [ ]:
print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}


In [ ]:
feature_names_all=v.get_feature_names_out()

array(['already', 'am', 'amazon', 'and', 'announcing', 'apple', 'are',
       'ate', 'biryani', 'dot', 'eating', 'eco', 'google', 'grapes',
       'iphone', 'ironman', 'is', 'loki', 'microsoft', 'model', 'new',
       'pixel', 'pizza', 'surface', 'tesla', 'thor', 'tomorrow', 'you'],
      dtype=object)

In [ ]:
feature_names_all=v.get_feature_names_out()
for i in feature_names_all:
  index=v.vocabulary_.get(i)
  idf_score =v.idf_[index]
  print(f'{i}:{idf_score}')


already:2.386294361119891
am:2.386294361119891
amazon:2.386294361119891
and:2.386294361119891
announcing:1.2876820724517808
apple:2.386294361119891
are:2.386294361119891
ate:2.386294361119891
biryani:2.386294361119891
dot:2.386294361119891
eating:1.9808292530117262
eco:2.386294361119891
google:2.386294361119891
grapes:2.386294361119891
iphone:2.386294361119891
ironman:2.386294361119891
is:1.1335313926245225
loki:2.386294361119891
microsoft:2.386294361119891
model:2.386294361119891
new:1.2876820724517808
pixel:2.386294361119891
pizza:2.386294361119891
surface:2.386294361119891
tesla:2.386294361119891
thor:2.386294361119891
tomorrow:1.2876820724517808
you:2.386294361119891


In [ ]:
print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}


In [ ]:
#here we used to find idf-score
all_feature_names=v.get_feature_names_out()
for word in all_feature_names:
  index=v.vocabulary_.get(word)
  idf_score=v.idf_[index]
  print(f'{word} : {idf_score}')

already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891


In [ ]:
corpus[:2]

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [ ]:
transform_output.toarray()[:2]

array([[0.24266547, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24266547, 0.        , 0.        ,
        0.40286636, 0.        , 0.        , 0.        , 0.        ,
        0.24266547, 0.11527033, 0.24266547, 0.        , 0.        ,
        0.        , 0.        , 0.72799642, 0.        , 0.        ,
        0.24266547, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.30652086,
        0.5680354 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5680354 ,
        0.        , 0.26982671, 0.        , 0.        , 0.        ,
        0.30652086, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30652086, 0.        ]])

fake news classification using word vector

In [ ]:
import pandas as pd
d=pd.read_csv('/content/Fake_Real_Data.csv',error_bad_lines=False,engine='python')
df=pd.DataFrame(d)
df

<ipython-input-9-629949838685>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  d=pd.read_csv('/content/Fake_Real_Data.csv',error_bad_lines=False,engine='python')
Skipping line 1604: unexpected end of data


Text label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1     U.S. conservative leader optimistic of common ...  Real
2     Trump proposes U.S. tax overhaul, stirs concer...  Real
3      Court Forces Ohio To Allow Millions Of Illega...  Fake
4     Democrats say Trump agrees to work on immigrat...  Real
...                                                 ...   ...
1597  Exclusive: Contenders emerge for No.2 Fed job,...  Real
1598  Senate repeals Labor Dept. municipal retiremen...  Real
1599   The Polls From Trump’s Horrific Week Have Bee...  Fake
1600  Embattled Alabama Republican Senate candidate ...  Real
1601  Sessions refuses to discuss conversations with...  Real

[1602 rows x 2 columns]

In [ ]:
!python -m spacy download en_core_web_lg

2023-08-20 11:02:34.806844: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [ ]:
import spacy
nlp= spacy.load('en_core_web_lg')

In [ ]:

df['vector']=df['Text'].apply(lambda x: nlp(x).vector)

In [ ]:
df['new_label']=df['label'].apply(lambda x:1 if x=='Real' else 0 )


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.vector.values,df.new_label,test_size=0.2,random_state=85)


In [ ]:
df

In [ ]:
x_train.shape

(1281,)

In [ ]:
x_test.shape

(321,)

In [ ]:
x_train

array([array([-1.5900251e+00,  7.0264083e-01, -1.6299601e+00,  9.4579285e-01,
               4.9461398e+00,  7.6340747e-01,  2.6494285e-01,  3.3257935e+00,
               3.5600248e-01, -1.6383759e+00,  4.8104830e+00,  1.4573253e+00,
              -3.7115545e+00,  4.9384525e-01, -2.6647180e-01,  3.0966327e+00,
               9.1145945e-01,  6.8541884e-01, -9.9697107e-01, -1.1602373e+00,
               1.4182152e+00, -1.2472373e+00, -6.9461262e-01,  8.1216162e-01,
              -1.8843701e-01, -1.4637522e+00, -2.2042208e+00, -1.4873774e-01,
              -4.8295197e-01,  6.4816010e-01,  8.1285536e-01,  3.4107229e-01,
              -8.0344099e-01, -1.8326967e+00, -2.4339366e+00, -1.2250046e+00,
              -7.6542598e-01,  5.6864828e-01,  1.3697401e-01, -8.7994027e-01,
               3.2495447e-02, -1.7902823e-01, -6.0174093e-02,  4.2448658e-01,
              -1.6786947e+00,  7.4382937e-01,  9.9770486e-01, -1.8989561e+00,
              -8.7691927e-01,  2.4352586e+00, -1.7060386e+00,  1

In [ ]:
import numpy as np
x_train_2d=np.stack(x_train)
x_test_2d=np.stack(x_test)

In [ ]:
type(x_train)

numpy.ndarray

In [ ]:
x_train_2d

array([[-1.5900251 ,  0.70264083, -1.6299601 , ..., -1.4493555 ,
        -1.2438276 ,  0.70433134],
       [-1.0108567 ,  1.4115386 , -3.102094  , ...,  0.14964852,
        -3.3547516 ,  1.2625562 ],
       [-1.4168184 ,  0.57172906, -1.4777199 , ..., -0.30491012,
        -1.9501319 ,  1.5461208 ],
       ...,
       [-1.5724461 , -0.1062293 , -0.38633588, ..., -1.3288858 ,
        -0.59983844,  0.8870459 ],
       [-1.3724457 ,  1.2073929 , -2.3381257 , ..., -0.07285976,
        -3.0352602 ,  0.84838015],
       [-2.343127  ,  0.43488717, -2.1020808 , ..., -1.9608403 ,
        -2.0759552 ,  1.0923419 ]], dtype=float32)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
mx=MinMaxScaler()
#minmaxscaler is used because our data has both positive and negative vector values, to sclae those values we used MinMaxScaler.
scaled_train_embed=mx.fit(x_train_2d)
scaled_test_embed=mx.fit(x_test_2d)

In [ ]:
train_embed=np.array(scaled_train_embed).reshape(-1,1)

In [ ]:
model=KNeighborsClassifier()
model.fit(x_train_2d,y_train)


KNeighborsClassifier()

In [ ]:
y_pred=model.predict(x_test_2d)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       149
           1       0.98      0.98      0.98       172

    accuracy                           0.98       321
   macro avg       0.98      0.98      0.98       321
weighted avg       0.98      0.98      0.98       321



In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm')

In [ ]:
doc=nlp('Dr. strange loves pav bhaji of mumbai. Hulk loves chaat of delhi ')
for sentences in doc.sents:
  print(sentences)

Dr. strange loves pav bhaji of mumbai.
Hulk loves chaat of delhi


In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
import nltk
from nltk.tokenize import sent_tokenize
sent_tokenize('Dr. strange loves pav bhaji of mumbai. Hulk loves chaat of delhi ')

['Dr. strange loves pav bhaji of mumbai.', 'Hulk loves chaat of delhi']

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS
from nltk.corpus import stopwords

In [ ]:
word_tokenize('Dr. strange loves pav bhaji of mumbai. Hulk loves chaat of delhi ')

['Dr.',
 'strange',
 'loves',
 'pav',
 'bhaji',
 'of',
 'mumbai',
 '.',
 'Hulk',
 'loves',
 'chaat',
 'of',
 'delhi']