In [ ]:
import pandas as pd
d=pd.read_csv('/content/Restaurant_Reviews.csv')
df=pd.DataFrame(d)
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
!python -m spacy download en_core_web_lg

2023-09-24 14:45:55.721886: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 1.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [ ]:
import spacy
nlp=spacy.load('en_core_web_sm')
def preprocess(text):
  doc=nlp(text)
  filtered_tokens=[]
  for token in doc:
    if not token.is_stop and not token.is_punct:
      filtered_tokens.append(token.lemma_)
  return wv.get_mean_vector(filtered_tokens)
preprocess('Wow... Loved this place')


array([-0.00432171,  0.01503511,  0.01686744,  0.00275164, -0.05210575,
       -0.03599801,  0.06197436, -0.07971317,  0.01631892,  0.07010972,
       -0.02927489, -0.0325147 , -0.00265863, -0.01938442, -0.01802341,
        0.05478759,  0.05240113,  0.02661064,  0.01819301, -0.02691923,
        0.00640196,  0.01536629,  0.04840272, -0.03898136,  0.02033635,
       -0.02783314, -0.00597133,  0.01573971,  0.01467471, -0.04181931,
       -0.06777313,  0.06406081, -0.01331423,  0.02723513,  0.01809668,
       -0.0106057 ,  0.04640351,  0.00611335, -0.00026489,  0.09874218,
        0.03950181, -0.06423587,  0.08289494,  0.03750614,  0.01935773,
       -0.03190827,  0.01923716, -0.01247198, -0.01611892,  0.05403563,
       -0.05238016,  0.07282311, -0.01150639, -0.02418922, -0.00592994,
        0.01156887, -0.00418907, -0.02679581,  0.02422242, -0.05828619,
        0.0062768 , -0.0259348 , -0.01894675, -0.01763773, -0.03075427,
       -0.0611959 , -0.06703851,  0.0210202 , -0.03643162,  0.05

In [ ]:
df['Review'][5]

'Now I am getting angry and I want my damn pho.'

In [ ]:
preprocess('do not worry if you do not want to come')

array([ 3.72672342e-02,  3.66718620e-02,  2.67493185e-02,  4.20418940e-02,
       -7.50001892e-02,  8.95539019e-03,  8.75263512e-02,  1.37707954e-02,
        1.35662733e-02,  3.34264562e-02, -2.21895818e-02, -3.94621529e-02,
       -1.94751136e-02, -5.71400998e-03, -6.71693534e-02,  8.86780396e-02,
        5.80708236e-02,  9.05794501e-02,  5.86222997e-03, -4.52741496e-02,
       -7.82573223e-02,  3.46393101e-02,  3.63291986e-02,  2.97762919e-02,
        8.03901032e-02,  5.57735674e-02,  1.47155719e-02, -5.76016009e-02,
        1.12424493e-02, -5.84597290e-02, -1.15035297e-02,  2.65374035e-03,
       -2.32248884e-02, -7.05800131e-02,  2.61287745e-02, -7.49768922e-03,
        4.92548756e-02,  1.67704485e-02,  1.18587464e-02,  5.25066219e-02,
        2.27381513e-02, -3.60300355e-02,  7.08272159e-02, -4.32570418e-03,
       -6.70152828e-02, -6.94270730e-02, -1.36185018e-02, -1.88993905e-02,
       -7.71285454e-03,  7.66049838e-03, -5.40368445e-02,  6.80753365e-02,
       -5.38146542e-03,  

In [ ]:
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', df['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 1500)

# X contains corpus (dependent variable)
X = cv.fit_transform(corpus).toarray()

# y contains answers if review
# is positive or negative
y = df.iloc[:, 1].values

In [ ]:
from sklearn.model_selection import train_test_split

# experiment with "test_size"
# to get better results
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# n_estimators can be said as number of
# trees, experiment with n_estimators
# to get better results
model = RandomForestClassifier(n_estimators = 501,
                            criterion = 'entropy')

model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=501)

In [ ]:
y_pred = model.predict(X_test)

y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.79      0.69      0.74       145
           1       0.63      0.74      0.68       105

    accuracy                           0.71       250
   macro avg       0.71      0.72      0.71       250
weighted avg       0.72      0.71      0.71       250



In [ ]:
def prediction(text):
  review = re.sub('[^a-zA-Z]', ' ', df['Review'][i])
  review = review.lower()
  reviews = review.split()
  sample_reviews=[word for word in reviews if not word in stopwords.words('english')]
  ps = PorterStemmer()
  review = [ps.stem(word) for word in sample_reviews]
  review = ' '.join(review)
  temp=cv.transform([review]).toarray()
  #print(temp)
  return model.predict(temp)
prediction('food is too good')


array([0])

In [ ]:
text=['good food']
if prediction(text):
  print('positive')
else:
  print('negative')

negative


In [ ]:
df['vector']=df['Review'].apply(lambda x: nlp(x).vector)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.vector.values,df.Liked,test_size=0.2,random_state=85)


In [ ]:
x_train.shape

(800,)

In [ ]:
x_train

array([array([ 0.4130053 ,  0.05697855,  0.13738568,  0.01395513, -0.23496754,
               0.2789194 ,  0.08281738,  0.37829766, -0.12334508,  0.06000969,
               0.75608236, -0.16301574, -0.04234174,  0.67134804, -0.602418  ,
              -0.09558628, -0.39627624,  0.01084905, -0.14490713,  0.36634544,
              -0.08144118, -0.06726101,  0.33594152, -0.68943816,  0.22830729,
               0.07446595,  0.514362  , -0.01535907,  0.17218296,  0.60213137,
               0.0627341 ,  0.30375916,  0.4159265 , -0.8435335 , -0.09797984,
               0.07268389, -0.11089166, -0.22188738, -0.33576712,  0.5965405 ,
              -0.2319795 ,  0.63031286,  0.24257657,  0.06363992,  0.07631983,
               0.15248397, -0.32377   ,  0.43080384,  0.5308991 ,  0.10647628,
               0.39544466, -0.16974102,  0.04401447, -0.1807746 ,  0.246978  ,
              -0.22305736, -0.11514088,  0.11358245, -0.07897113, -0.19877832,
              -0.01911674, -0.4113287 , -0.3477177 ,

In [ ]:
import numpy as np
x_train_2d=np.stack(x_train)
x_test_2d=np.stack(x_test)

In [ ]:
x_train_2d

array([[ 0.4130053 ,  0.05697855,  0.13738568, ...,  0.21041735,
        -0.40172502, -0.03807474],
       [-0.24935126, -0.33764347,  0.31228885, ...,  0.2824919 ,
        -0.13304293, -0.26894563],
       [ 0.5881547 , -0.13987193, -0.31175414, ...,  0.4551045 ,
        -0.509403  ,  0.09765875],
       ...,
       [-0.27458537, -0.47897026, -0.05023032, ...,  0.15250762,
        -0.68174493,  0.09163761],
       [ 0.39220324, -0.579296  , -0.29032764, ...,  0.25836197,
        -0.1467776 , -0.00331803],
       [-0.5425375 , -0.75447947, -0.02449408, ...,  0.09216732,
        -0.58605653,  0.738475  ]], dtype=float32)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
mx=MinMaxScaler()
#minmaxscaler is used because our data has both positive and negative vector values, to sclae those values we used MinMaxScaler.
scaled_train_embed=mx.fit(x_train_2d)
scaled_test_embed=mx.fit(x_test_2d)

In [ ]:
scaled_train_embed

MinMaxScaler()

In [ ]:
x_train_2d=np.array(x_train_2d).reshape(-1,1)
x_test_2d=np.array(x_test_2d).reshape(-1,1)

In [ ]:
x_train_2d.shape

(76800, 1)

In [ ]:
x_test_2d.shape

(19200, 1)

In [ ]:
import numpy as np
x_train

In [ ]:
model=KNeighborsClassifier()
model.fit(x_train_2d,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=model.predict(x_test_2d)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.59      0.60      0.60       100
           1       0.60      0.59      0.59       100

    accuracy                           0.59       200
   macro avg       0.60      0.59      0.59       200
weighted avg       0.60      0.59      0.59       200



In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
model1=SVC()
model1.fit(x_train_2d,y_train)

ValueError: ignored

In [ ]:
x_train_2d


array([[ 0.4130053 ,  0.05697855,  0.13738568, ...,  0.21041735,
        -0.40172502, -0.03807474],
       [-0.24935126, -0.33764347,  0.31228885, ...,  0.2824919 ,
        -0.13304293, -0.26894563],
       [ 0.5881547 , -0.13987193, -0.31175414, ...,  0.4551045 ,
        -0.509403  ,  0.09765875],
       ...,
       [-0.27458537, -0.47897026, -0.05023032, ...,  0.15250762,
        -0.68174493,  0.09163761],
       [ 0.39220324, -0.579296  , -0.29032764, ...,  0.25836197,
        -0.1467776 , -0.00331803],
       [-0.5425375 , -0.75447947, -0.02449408, ...,  0.09216732,
        -0.58605653,  0.738475  ]], dtype=float32)

In [ ]:
y_pred=model1.predict(x_test_2d)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.67      0.67      0.67       102
           1       0.66      0.66      0.66        98

    accuracy                           0.67       200
   macro avg       0.66      0.66      0.66       200
weighted avg       0.67      0.67      0.67       200

